version: '3'
services:
   flask_app:                     # service name
        build:                    # we can give Dockerfile or the image name if its already build
          context: .
          dockerfile: Dockerfile
        command: python app.py    # Entry point command can be overrided here
        ports:
           - "5000:5000"          # port mapping
   nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_app
    ports:
      - "80:80" 

