version: '3.2'
services:
   flask_app:                     # service name
        build:                    # we can give Dockerfile or the image name if its already build
          context: .
          dockerfile: Dockerfile
        command: python app.py    # Entry point command can be overrided here
        ports:
           - "5000:5000"          # port mapping
        volumes:
           - type: bind
             source: ./app.py
             target: /usr/src/app/app.py
        environment:
          - DEBUG=1 

