version: '3'
services:
   flask_app:                     # service name
        build:                    # we can give Dockerfile or the image name if its already build
          context: .
          dockerfile: Dockerfile
        command: python app.py    # Entry point command can be overrided here
        ports:
           - "5000:5000"          # port mapping
        

